import json, sys
import os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import w1
levels = [w1.level1(), w1.level2(), w1.level3(), w1.level4()]
try:
    import w2; levels += [w2.level5(), w2.level6(), w2.level7(), w2.level8()]
except ImportError: pass
try:
    import w3; levels += [w3.level9(), w3.level10(), w3.level11(), w3.level12()]
except ImportError: pass
names = ['Sáng Trên Đồi', 'Rừng Tre', 'Thác Bạc', 'Hang Rễ', 'Hẻm Đá Đỏ', 'Biển Cát', 'Phế Tích', 'Đền Mặt Trời', 'Sườn Tuyết', 'Hang Pha Lê', 'Cầu Gió', 'Tháp Đèn']
themes = ['meadow', 'meadow', 'meadow', 'cave', 'desert', 'desert', 'desert', 'temple', 'snow', 'crystal', 'snow', 'tower']
out = ['/* ── Levels (generated by design/gen.py — edit the Python, not this file) ── */', 'const LEVELS = [']
have = {l['id']: l for l in levels}
for i in range(12):
    lid = i + 1
    if lid in have:
        l = have[lid]
        rows = l['grid'].rows()
        meta = {k: v for k, v in l.items() if k not in ('grid',)}
    else:  # placeholder until designed
        rows = [' ' * 40] * 12 + ['P' + ' ' * 36 + 'G  '] + ['#' * 40] * 3
        meta = dict(id=lid, name=names[i], theme=themes[i], signs=[])
    meta.setdefault('maze', False)
    body = json.dumps(meta, ensure_ascii=False)[1:-1]
    out.append('  { ' + body + ', map: `\n' + '\n'.join(rows) + '\n` },')
out.append('];')
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', '10-levels.js'), 'w').write('\n'.join(out) + '\n')
print('levels written:', sorted(have))
