/* ── Content. Nothing here is a rule about regions: symbols go wherever history puts them. ── */
const START_HAND = 3;
/* each symbol resolves into steps; a card resolves its symbols left to right */
const SYM = {
  A: { name: 'Đánh', desc: 'Gây 1 sát thương (trúng tường trước).', steps: [{ dmg: 1, basic: 1 }] },
  W: { name: 'Tường', desc: 'Lá này ở lại làm công trình, mỗi biểu tượng tường là 1 độ bền.', steps: [] },
  H: { name: 'Hồi', desc: 'Hồi 1 máu.', steps: [{ heal: 1 }] },
  M: { name: 'Thêm lượt', desc: 'Đánh thêm một lá.', steps: [{ plays: 1 }] },
  D: { name: 'Rút bài', desc: 'Rút 1 lá.', steps: [{ draw: 1 }] },
  G: { name: 'Vàng', desc: 'Nhận 1 vàng để thuê lính ở chợ.', steps: [{ gold: 1 }] },
  R: { name: 'Phá', desc: 'Phá sập công trình lớn nhất của đối thủ (kỳ quan mất 2 độ bền).', steps: [{ raze: 1 }] },
  S: { name: 'Cướp', desc: 'Lấy ngẫu nhiên 1 lá trên tay đối thủ.', steps: [{ steal: 1 }] },
  C: { name: 'Cải đạo', desc: 'Kéo công trình lớn nhất của đối thủ về phe mình.', steps: [{ convert: 1 }] },
  K: { name: 'Kỵ binh', desc: 'Gây 2 sát thương. Lạc đà chặn được.', steps: [{ dmg: 2, cav: 1 }] },
  E: { name: 'Voi chiến', desc: 'Phá sập một công trình rồi gây thêm 1 sát thương.', steps: [{ raze: 1 }, { dmg: 1 }] },
  L: { name: 'Lạc đà', desc: 'Gây 1 sát thương, rồi dựng chốt lạc đà: đòn kỵ binh kế tiếp nhắm vào bạn bị hủy (ngựa sợ lạc đà).', steps: [{ dmg: 1 }, { token: 'camel' }] },
  B: { name: 'Bắn xa', desc: 'Gây 1 sát thương thẳng vào thành, bay qua tường.', steps: [{ dmg: 1, pierce: 1 }] },
  F: { name: 'Hỏa khí', desc: 'Gây 1 sát thương cho mọi đối thủ.', steps: [{ dmg: 1, all: 1 }] },
  Y: { name: 'Đại bàng', desc: 'Gây 1 sát thương; đối thủ không có tường thì gây thêm 1.', steps: [{ dmg: 1, eagle: 1 }] },
  N: { name: 'Thuyền', desc: 'Đổ bộ: cướp 1 lá rồi gây 1 sát thương.', steps: [{ steal: 1 }, { dmg: 1 }] },
};
const SYM_ORDER = 'AKEBLYFNRSCWHMDG';
const COMMON_NAMES = {
  A: 'Bộ binh', AA: 'Kiếm sĩ', AAA: 'Đội xung kích', AM: 'Tập kích', AAM: 'Đột kích', AD: 'Trinh sát', AH: 'Lính giáo',
  W: 'Hàng rào gỗ', WW: 'Tường đá', WWW: 'Thành lũy', WH: 'Tháp canh',
  H: 'Lương thực', HH: 'Thầy thuốc', HD: 'Tu viện', MD: 'Sứ giả', MM: 'Thần tốc', D: 'Do thám', DD: 'Học giả',
  G: 'Thương nhân', GG: 'Mỏ vàng', GD: 'Chợ phiên', R: 'Xe phá thành', S: 'Gián điệp', C: 'Thầy tu',
  K: 'Kỵ binh', KM: 'Kỵ binh nhẹ', KK: 'Kỵ binh nặng', E: 'Voi chiến', EA: 'Voi xung trận', L: 'Kỵ binh lạc đà', LG: 'Thương đoàn',
  B: 'Cung thủ', BB: 'Mưa tên', BM: 'Kỵ xạ', F: 'Hỏa tiễn', FF: 'Pháo', Y: 'Chiến binh Đại bàng', YM: 'Đại bàng săn mồi', N: 'Thuyền chiến', NM: 'Thuyền đổ bộ',
};
/* signature cards: steps written by hand. wall kinds: regen (+1 mỗi lượt), sacred (hồi máu chủ mỗi lượt), thorns (ai đánh vào mất 1), fortress (bị phá chỉ mất 1 độ bền), wonder */
const UNIQUE = {
  greatwall:  { name: 'Vạn Lý Trường Thành', icons: 'WWWW', text: 'Tường 4 độ bền.', wall: 4 },
  exam:       { name: 'Khoa cử', icons: 'DDG', text: 'Rút 2 lá, nhận 1 vàng.', steps: [{ draw: 2 }, { gold: 1 }] },
  samurai:    { name: 'Samurai', icons: 'AA', text: 'Gây 2 sát thương; đối thủ không có tường thì gây 3.', steps: [{ dmg: 2, samurai: 1 }] },
  kamikaze:   { name: 'Thần phong', icons: 'D', text: 'Bão thần nổi lên: tới lượt sau của bạn, mọi đòn nhắm vào bạn vô hiệu. Rút 1 lá.', steps: [{ token: 'immune' }, { draw: 1 }] },
  hwacha:     { name: 'Xe Hwacha', icons: 'FF', text: 'Gây 1 sát thương cho mọi đối thủ, hai lần.', steps: [{ dmg: 1, all: 1 }, { dmg: 1, all: 1 }] },
  tripitaka:  { name: 'Bát vạn Đại Tạng Kinh', icons: 'DDD', text: 'Rút 3 lá.', steps: [{ draw: 3 }] },
  ironcav:    { name: 'Thiết Phù Đồ', icons: 'KA', text: 'Kỵ binh sắt: gây 3 sát thương. Lạc đà chặn được.', steps: [{ dmg: 3, cav: 1 }] },
  thunder:    { name: 'Bom sấm sét', icons: 'RF', text: 'Phá một công trình, rồi gây 1 sát thương cho mọi đối thủ.', steps: [{ raze: 1 }, { dmg: 1, all: 1 }] },
  stakes:     { name: 'Cọc Bạch Đằng', icons: 'W', text: 'Cắm cọc chờ nước rút: tới lượt sau của bạn, đối thủ đầu tiên gây sát thương cho bạn mất 2 máu.', steps: [{ token: 'trap' }] },
  proclaim:   { name: 'Hịch tướng sĩ', icons: 'HHDD', text: 'Hồi 2 máu, rút 2 lá.', steps: [{ heal: 2 }, { draw: 2 }] },
  caravan:    { name: 'Thương đoàn sa mạc', icons: 'LGD', text: 'Gây 1 sát thương, dựng chốt lạc đà, nhận 1 vàng, rút 1 lá.', steps: [{ dmg: 1 }, { token: 'camel' }, { gold: 1 }, { draw: 1 }] },
  baghdad:    { name: 'Bệnh viện Baghdad', icons: 'HHH', text: 'Hồi 3 máu.', steps: [{ heal: 3 }] },
  immortals:  { name: 'Đội Bất tử', icons: 'WW', text: 'Tường 2 độ bền, mỗi lượt của bạn tự hồi 1 độ bền (tối đa 3).', wall: 2, kind: 'regen' },
  sasanian:   { name: 'Voi chiến Sasanian', icons: 'EE', text: 'Phá hai công trình, gây 2 sát thương.', steps: [{ raze: 1 }, { dmg: 1 }, { raze: 1 }, { dmg: 1 }] },
  urban:      { name: 'Đại pháo Urban', icons: 'RR', text: 'Phá sập mọi công trình của một đối thủ, rồi gây 1 sát thương.', steps: [{ raze: 9 }, { dmg: 1 }] },
  janissary:  { name: 'Tân quân Janissary', icons: 'AAM', text: 'Gây 2 sát thương, đánh thêm một lá.', steps: [{ dmg: 2 }, { plays: 1 }] },
  mansa:      { name: 'Mansa Musa hành hương', icons: 'GGGM', text: 'Nhận 3 vàng; lần thuê lính kế tiếp trong lượt này miễn phí; đánh thêm một lá.', steps: [{ gold: 3 }, { buyFree: 1 }, { plays: 1 }] },
  sankore:    { name: 'Đại học Sankore', icons: 'DDH', text: 'Rút 2 lá, hồi 1 máu.', steps: [{ draw: 2 }, { heal: 1 }] },
  lalibela:   { name: 'Nhà thờ đá Lalibela', icons: 'WWW', text: 'Tường 3 độ bền; còn đứng thì mỗi lượt bạn hồi 1 máu.', wall: 3, kind: 'sacred' },
  shotel:     { name: 'Chiến binh Shotel', icons: 'AAM', text: 'Gây 2 sát thương, đánh thêm một lá.', steps: [{ dmg: 2 }, { plays: 1 }] },
  arrowrain:  { name: 'Mưa tên du mục', icons: 'BB', text: 'Gây 1 sát thương bay qua tường cho mọi đối thủ.', steps: [{ dmg: 1, pierce: 1, all: 1 }] },
  feint:      { name: 'Giả rút lui', icons: 'RKA', text: 'Dụ địch ra khỏi tường: phá một công trình, rồi gây 2 sát thương.', steps: [{ raze: 1 }, { dmg: 2 }] },
  scourge:    { name: 'Tai họa của Chúa', icons: 'FS', text: 'Mọi đối thủ bỏ 1 lá ngẫu nhiên và mất 1 máu.', steps: [{ discard: 1, all: 1 }, { dmg: 1, all: 1 }] },
  aquileia:   { name: 'Cướp phá Aquileia', icons: 'SS', text: 'Cướp 2 lá của một đối thủ.', steps: [{ steal: 2 }] },
  twocourts:  { name: 'Hai triều Nam Bắc', icons: 'GGDM', text: 'Nhận 2 vàng, rút 1 lá, đánh thêm một lá.', steps: [{ gold: 2 }, { draw: 1 }, { plays: 1 }] },
  ordo:       { name: 'Trại Ordo', icons: 'WWH', text: 'Tường 2 độ bền, hồi 1 máu.', wall: 2, steps: [{ heal: 1 }] },
  longbow:    { name: 'Mưa tên trường cung', icons: 'BB', text: 'Gây 2 sát thương bay qua tường.', steps: [{ dmg: 2, pierce: 1 }] },
  charter:    { name: 'Đại Hiến chương', icons: 'GGH', text: 'Nhận 2 vàng, hồi 1 máu, rút 1 lá.', steps: [{ gold: 2 }, { heal: 1 }, { draw: 1 }] },
  woad:       { name: 'Cuồng chiến Woad', icons: 'AAA', text: 'Gây 3 sát thương, bạn mất 1 máu.', steps: [{ dmg: 3 }, { self: 1 }] },
  ambush:     { name: 'Phục kích cao nguyên', icons: 'FD', text: 'Gây 1 sát thương cho mọi đối thủ, rút 1 lá.', steps: [{ dmg: 1, all: 1 }, { draw: 1 }] },
  paladin:    { name: 'Hiệp sĩ Paladin', icons: 'KK', text: 'Gây 4 sát thương. Lạc đà chặn được.', steps: [{ dmg: 4, cav: 1 }] },
  charlemagne:{ name: 'Charlemagne', icons: 'HHW', text: 'Hồi 2 máu, mọi công trình của bạn +1 độ bền.', steps: [{ heal: 2 }, { fortify: 1 }] },
  berserk:    { name: 'Berserker', icons: 'AAH', text: 'Gây 2 sát thương, hồi 1 máu.', steps: [{ dmg: 2 }, { heal: 1 }] },
  lindisfarne:{ name: 'Cướp phá Lindisfarne', icons: 'NS', text: 'Cướp 2 lá rồi gây 1 sát thương.', steps: [{ steal: 2 }, { dmg: 1 }] },
  teutonic:   { name: 'Hiệp sĩ dòng Teuton', icons: 'WWA', text: 'Tường 2 độ bền có gai: ai đánh vào nó mất 1 máu.', wall: 2, kind: 'thorns' },
  marienburg: { name: 'Thành Marienburg', icons: 'WWWW', text: 'Tường 4 độ bền.', wall: 4 },
  horde:      { name: 'Biển người', icons: 'MMD', text: 'Đánh thêm 2 lá, rút 1 lá.', steps: [{ plays: 2 }, { draw: 1 }] },
  sackrome:   { name: 'Cướp phá Rome năm 410', icons: 'RSA', text: 'Phá một công trình, cướp 1 lá, gây 1 sát thương.', steps: [{ raze: 1 }, { steal: 1 }, { dmg: 1 }] },
  conquist:   { name: 'Conquistador', icons: 'BB', text: 'Súng và ngựa: gây 2 sát thương bay qua tường.', steps: [{ dmg: 2, pierce: 1 }] },
  reconq:     { name: 'Reconquista', icons: 'FH', text: 'Gây 1 sát thương cho mọi đối thủ, hồi 1 máu.', steps: [{ dmg: 1, all: 1 }, { heal: 1 }] },
  caravel:    { name: 'Thuyền buồm Caravel', icons: 'NDM', text: 'Cướp 1 lá, rút 1 lá, đánh thêm một lá.', steps: [{ steal: 1 }, { draw: 1 }, { plays: 1 }] },
  indiaroute: { name: 'Đường biển tới Ấn Độ', icons: 'GGGM', text: 'Nhận 3 vàng, đánh thêm một lá.', steps: [{ gold: 3 }, { plays: 1 }] },
  theodosius: { name: 'Tường Theodosius', icons: 'WWW', text: 'Tường 3 độ bền, mỗi lượt tự hồi 1 độ bền (tối đa 4).', wall: 3, kind: 'regen' },
  greekfire:  { name: 'Lửa Hy Lạp', icons: 'RAA', text: 'Phá một công trình, rồi gây 2 sát thương.', steps: [{ raze: 1 }, { dmg: 2 }] },
  sacrifice:  { name: 'Hiến tế', icons: 'DDM', text: 'Bạn mất 1 máu, rút 2 lá, đánh thêm một lá.', steps: [{ self: 1 }, { draw: 2 }, { plays: 1 }] },
  flowerwar:  { name: 'Chiến tranh hoa', icons: 'SY', text: 'Bắt tù binh: cướp 1 lá, rồi đòn Đại bàng.', steps: [{ steal: 1 }, { dmg: 1, eagle: 1 }] },
  chichen:    { name: 'Kỳ quan Chichén Itzá', icons: 'WWW', text: 'Kỳ quan 4 độ bền, hứng mọi đòn trước cả tường. Còn đứng tới đầu lượt thứ ba sau khi xây thì bạn thắng. Phá, Voi, pháo trừ 2 độ bền.', wonder: 1 },
  calendar:   { name: 'Lịch Maya', icons: 'DDH', text: 'Rút 2 lá, hồi 1 máu.', steps: [{ draw: 2 }, { heal: 1 }] },
  incaroad:   { name: 'Đường Inca', icons: 'MDD', text: 'Đánh thêm một lá, rút 2 lá.', steps: [{ plays: 1 }, { draw: 2 }] },
  sacsay:     { name: 'Pháo đài Sacsayhuamán', icons: 'WWW', text: 'Tường 3 độ bền bằng đá khổng lồ: bị phá chỉ mất 1 độ bền.', wall: 3, kind: 'fortress' },
  angkor:     { name: 'Kỳ quan Angkor Wat', icons: 'WWW', text: 'Kỳ quan 4 độ bền, hứng mọi đòn trước cả tường. Còn đứng tới đầu lượt thứ ba sau khi xây thì bạn thắng. Phá, Voi, pháo trừ 2 độ bền.', wonder: 1 },
  baray:      { name: 'Hồ Baray', icons: 'HHG', text: 'Hồi 2 máu, nhận 1 vàng.', steps: [{ heal: 2 }, { gold: 1 }] },
  armoredel:  { name: 'Voi chiến bọc giáp', icons: 'EE', text: 'Phá hai công trình, gây 2 sát thương.', steps: [{ raze: 1 }, { dmg: 1 }, { raze: 1 }, { dmg: 1 }] },
  cholafleet: { name: 'Hạm đội Chola', icons: 'NF', text: 'Gây 1 sát thương cho mọi đối thủ, rồi cướp 1 lá.', steps: [{ dmg: 1, all: 1 }, { steal: 1 }] },
};
/* civs: hp2 (1v1) and hp4 (3–4 players) come from tune.js — AI vs AI until every civ wins 41–59% of duels and 17–30% of 4-player games; deck = 24 cards; group only helps browsing */
const CIVS = {
  trunghoa:  { name: 'Trung Hoa', group: 'Đông Á', color: '#b3261e', charge: 'sun', hp2: 12, hp4: 12, style: 'Hỏa khí, tường lớn, khoa cử', deck: 'A3 AA1 AM2 F3 FF1 W2 WW1 WH1 H2 HD1 DD1 G1 R1 AA1 C1 +greatwall +exam' },
  nhat:      { name: 'Nhật', group: 'Đông Á', color: '#c0392b', charge: 'disc', hp2: 10, hp4: 12, style: 'Samurai đánh thẳng, bão thần che chắn', deck: 'A5 AA2 AM2 AAM1 K1 B2 W2 WH1 H2 HH1 D1 MD1 G1 +samurai +kamikaze' },
  caoly:     { name: 'Cao Ly', group: 'Đông Á', color: '#2b6cb0', charge: 'knot', hp2: 15, hp4: 15, style: 'Xe hỏa tiễn, thủ chắc, rút bài', deck: 'A4 AA2 AM1 F3 B2 W1 WW1 WH1 H2 HH1 DD1 D1 G1 R1 +hwacha +tripitaka' },
  nuchan:    { name: 'Nữ Chân', group: 'Đông Á', color: '#3d4f5c', charge: 'axe', hp2: 8, hp4: 11, style: 'Kỵ binh sắt, bom sấm sét', deck: 'A5 AA2 AM1 AAM1 K2 KM1 KK1 F1 W2 WH1 H2 D1 G1 R1 +ironcav +thunder' },
  daiviet:   { name: 'Đại Việt', group: 'Đông Nam Á', color: '#b8860b', charge: 'star', hp2: 15, hp4: 13, style: 'Nỏ, voi, cọc Bạch Đằng', deck: 'A4 AA1 AM1 AD1 B3 BM1 E2 W2 WW1 WH1 H2 HH1 D1 G1 +stakes +proclaim' },
  khmer:     { name: 'Khmer', group: 'Đông Nam Á', color: '#8a5a2b', charge: 'temple', hp2: 8, hp4: 11, style: 'Voi chiến, kỳ quan Angkor', deck: 'A4 AA1 AM1 E2 EA1 B1 W2 WW1 WH1 H2 HH1 D1 G2 C1 R1 +angkor +baray' },
  ando:      { name: 'Ấn Độ', group: 'Nam Á', color: '#d97706', charge: 'wheel', hp2: 14, hp4: 13, style: 'Voi bọc giáp, hạm đội Chola', deck: 'A4 AA1 AM1 E2 EA1 N1 L1 W2 WH1 H2 HH1 HD1 D1 G1 C1 R1 +armoredel +cholafleet' },
  arap:      { name: 'Ả Rập', group: 'Trung Đông & châu Phi', color: '#1f7a4d', charge: 'crescent', hp2: 10, hp4: 11, style: 'Lạc đà, thương đoàn, y học', deck: 'A4 AM1 L3 LG1 K1 W2 WH1 H2 HH2 HD1 C1 G1 GD1 S1 +caravan +baghdad' },
  batu:      { name: 'Ba Tư', group: 'Trung Đông & châu Phi', color: '#6b2d8f', charge: 'sun', hp2: 12, hp4: 10, style: 'Voi và lạc đà, đội Bất tử', deck: 'A4 AA1 AM1 E2 EA1 L2 K1 W2 WH1 H2 HH1 D1 G1 R1 C1 +immortals +sasanian' },
  turks:     { name: 'Turks', group: 'Trung Đông & châu Phi', color: '#a51c30', charge: 'crescent', hp2: 13, hp4: 10, style: 'Đại pháo, tân quân, hỏa khí', deck: 'A4 AA1 AM2 F2 FF1 L1 K1 W2 WH1 H2 D1 G2 R2 +urban +janissary' },
  mali:      { name: 'Mali', group: 'Trung Đông & châu Phi', color: '#c08a1e', charge: 'disc', hp2: 7, hp4: 10, style: 'Vàng, lính đánh thuê, lạc đà', deck: 'A4 AM2 L2 LG1 G2 GG1 W2 WH1 H2 HH1 D1 S1 K1 AA1 +mansa +sankore' },
  ethiopia:  { name: 'Ethiopia', group: 'Trung Đông & châu Phi', color: '#2f7d32', charge: 'cross', hp2: 13, hp4: 9, style: 'Nhà thờ đá hồi máu, chiến binh Shotel', deck: 'A5 AA1 AM1 E1 L1 B1 W2 WW1 WH1 H2 HH2 HD1 C1 D1 G1 +lalibela +shotel' },
  mongco:    { name: 'Mông Cổ', group: 'Thảo nguyên', color: '#1f6f8b', charge: 'horse', hp2: 13, hp4: 11, style: 'Kỵ xạ dồn dập, giả rút lui', deck: 'A3 AM2 B3 BM3 K1 KM1 MD1 W1 WH1 H2 D1 S1 G1 R1 +arrowrain +feint' },
  hung:      { name: 'Hung', group: 'Thảo nguyên', color: '#7a3b12', charge: 'bow', hp2: 12, hp4: 13, style: 'Tàn phá, cướp bóc, kỵ xạ', deck: 'A4 AA1 AM2 AAM1 B2 BM2 K1 KM1 S2 W1 WH1 H2 D1 R1 +scourge +aquileia' },
  khietdan:  { name: 'Khiết Đan', group: 'Thảo nguyên', color: '#4a6b3a', charge: 'bow', hp2: 11, hp4: 10, style: 'Hai triều giàu có, trại du mục', deck: 'A4 AM1 B2 BM2 K2 KM1 W2 WH1 H2 HH1 D1 G2 R1 +twocourts +ordo' },
  briton:    { name: 'Briton', group: 'Châu Âu', color: '#9b1c1c', charge: 'tower', hp2: 13, hp4: 13, style: 'Trường cung bắn qua tường', deck: 'A3 AM1 B4 BB2 AD1 K1 W2 WW1 WH1 H2 HH1 D1 G1 R1 +longbow +charter' },
  celts:     { name: 'Celts', group: 'Châu Âu', color: '#1d6b45', charge: 'knot', hp2: 10, hp4: 13, style: 'Bộ binh cuồng chiến, phục kích', deck: 'A5 AA3 AM2 AAM1 AD1 AH1 W2 WH1 H2 HH1 D1 S1 R1 +woad +ambush' },
  frank:     { name: 'Frank', group: 'Châu Âu', color: '#1f4e9c', charge: 'fleur', hp2: 8, hp4: 11, style: 'Hiệp sĩ, lâu đài', deck: 'A4 AA1 AM1 K3 KK1 KM1 W2 WW1 WH1 H2 HH1 C1 D1 G1 R1 +paladin +charlemagne' },
  vikings:   { name: 'Vikings', group: 'Châu Âu', color: '#33506b', charge: 'ship', hp2: 10, hp4: 15, style: 'Thuyền rồng cướp phá, berserker', deck: 'A4 AA2 AM2 AAM1 N3 NM1 S1 W2 WH1 H2 HH1 D1 G1 +berserk +lindisfarne' },
  teutons:   { name: 'Teutons', group: 'Châu Âu', color: '#2d2d2d', charge: 'cross', hp2: 13, hp4: 11, style: 'Tường gai, hiệp sĩ nặng', deck: 'A3 AA2 K2 KK1 W3 WW2 WWW1 WH1 H2 HH1 C1 D1 R1 G1 +teutonic +marienburg' },
  goths:     { name: 'Goths', group: 'Châu Âu', color: '#5b4636', charge: 'axe', hp2: 10, hp4: 11, style: 'Biển người, cướp phá Rome', deck: 'A5 AA2 AM3 AAM1 MM1 AD1 W2 WH1 H3 D1 S1 R1 +horde +sackrome' },
  spanish:   { name: 'Spanish', group: 'Châu Âu', color: '#b45309', charge: 'tower', hp2: 12, hp4: 11, style: 'Conquistador, vàng, Reconquista', deck: 'A3 AA1 AM1 AH1 K2 KM1 B1 W2 WW1 WH1 H2 C1 D1 G2 GD1 R1 +conquist +reconq' },
  portuguese:{ name: 'Portuguese', group: 'Châu Âu', color: '#0e5e6f', charge: 'quinas', hp2: 10, hp4: 14, style: 'Thuyền buồm, thương mại biển', deck: 'A3 AA1 AM2 N2 NM1 B1 W2 WH1 H2 HH1 D1 MD1 G2 BB1 S1 +caravel +indiaroute' },
  byzantines:{ name: 'Byzantines', group: 'Châu Âu', color: '#5b2a86', charge: 'cross', hp2: 13, hp4: 11, style: 'Tường Theodosius, lửa Hy Lạp, kỵ binh giáp trụ', deck: 'A3 AA1 AM1 K2 W3 WW2 WH1 H2 HH2 HD1 C1 D1 G1 R1 +theodosius +greekfire' },
  aztecs:    { name: 'Aztecs', group: 'Châu Mỹ', color: '#0f766e', charge: 'eagle', hp2: 9, hp4: 12, style: 'Hiến tế, chiến binh Đại bàng', deck: 'A4 AA2 AM1 AAM1 Y3 YM1 B1 S1 W1 WH1 H2 HH1 D1 G1 C1 +sacrifice +flowerwar' },
  maya:      { name: 'Maya', group: 'Châu Mỹ', color: '#2e7d5b', charge: 'pyramid', hp2: 9, hp4: 15, style: 'Kỳ quan Chichén Itzá, cung thủ', deck: 'A4 AM1 Y2 B2 BB1 W2 WW1 WH1 H2 HH1 D1 DD1 G1 R1 C1 +chichen +calendar' },
  incas:     { name: 'Incas', group: 'Châu Mỹ', color: '#c2410c', charge: 'sun', hp2: 15, hp4: 13, style: 'Đường Inca thần tốc, pháo đài đá', deck: 'A3 AA1 AM2 MD1 B2 Y1 W2 WW1 WH1 H2 HH1 D1 G2 S1 R1 +incaroad +sacsay' },
};
const CIV_ORDER = Object.keys(CIVS);
const GROUPS = ['Đông Á', 'Đông Nam Á', 'Nam Á', 'Trung Đông & châu Phi', 'Thảo nguyên', 'Châu Âu', 'Châu Mỹ'];
/* the mercenary market: neutral cards anyone can hire with gold */
const MERCS = [
  { id: 'genoa', name: 'Lính nỏ Genoa', icons: 'BBM', cost: 2, n: 2 },
  { id: 'crusader', name: 'Thập tự quân', icons: 'KAM', cost: 2, n: 2 },
  { id: 'engineer', name: 'Kỹ sư công thành', icons: 'RWWM', cost: 2, n: 2 },
  { id: 'trebuchet', name: 'Máy bắn đá', icons: 'RR', cost: 3, n: 1, steps: [{ raze: 1 }, { raze: 1 }] },
  { id: 'physician', name: 'Thầy thuốc', icons: 'HHHD', cost: 2, n: 2 },
  { id: 'venetian', name: 'Thương nhân Venice', icons: 'GGDM', cost: 1, n: 2 },
  { id: 'varangian', name: 'Vệ binh Varangian', icons: 'KKWW', cost: 3, n: 1 },
  { id: 'cuman', name: 'Kỵ xạ Cuman', icons: 'BBM', cost: 2, n: 2 },
  { id: 'assassin', name: 'Thích khách', icons: 'BBB', cost: 3, n: 1, text: 'Gây 3 sát thương bay qua tường.', steps: [{ dmg: 3, pierce: 1 }] },
  { id: 'envoy', name: 'Sứ thần', icons: 'SSM', cost: 2, n: 1 },
  { id: 'templar', name: 'Hiệp sĩ dòng Đền', icons: 'CKH', cost: 3, n: 1 },
  { id: 'gunners', name: 'Pháo thủ Hungary', icons: 'FFF', cost: 3, n: 1 },
  { id: 'warel', name: 'Voi chiến thuê', icons: 'EA', cost: 2, n: 1 },
  { id: 'bedouin', name: 'Lạc đà Bedouin', icons: 'LLM', cost: 2, n: 1 },
];
/* the times: one event per round, the next one is always visible */
const EVENTS = [
  { id: 'plague', name: 'Dịch hạch', text: 'Mọi người mất 1 máu.' },
  { id: 'harvest', name: 'Mùa gặt', text: 'Mọi người hồi 1 máu.' },
  { id: 'silkroad', name: 'Thương lộ thông suốt', text: 'Mọi người nhận 1 vàng.' },
  { id: 'winter', name: 'Mùa đông khắc nghiệt', text: 'Mọi công trình mất 1 độ bền.' },
  { id: 'fair', name: 'Hội chợ lớn', text: 'Chợ thay 3 lá mới; vòng này thuê lính rẻ hơn 1 vàng.' },
  { id: 'feast', name: 'Lễ hội mùa xuân', text: 'Mọi người rút 1 lá.' },
  { id: 'revolt', name: 'Nổi loạn', text: 'Người nhiều máu nhất mất 1 máu.' },
  { id: 'crusade', name: 'Thập tự chinh', text: 'Vòng này mọi biểu tượng Đánh gây thêm 1 sát thương.' },
  { id: 'monsoon', name: 'Mùa mưa', text: 'Vòng này không ai dựng được công trình mới.' },
  { id: 'flood', name: 'Lũ lụt', text: 'Mọi người bỏ 1 lá ngẫu nhiên trên tay.' },
  { id: 'eclipse', name: 'Nhật thực', text: 'Mọi người chuyển 1 lá ngẫu nhiên cho người kế tiếp.' },
  { id: 'bells', name: 'Chuông nguyện', text: 'Người ít máu nhất hồi 2 máu.' },
];
/* relics: pick 1 of 3 at the start */
const RELICS = {
  joyeuse: { name: 'Kiếm Joyeuse', text: 'Lá gây sát thương đầu tiên mỗi lượt gây thêm 1.' },
  grail:   { name: 'Chén Thánh', text: 'Lá hồi máu đầu tiên mỗi lượt hồi thêm 1.' },
  scone:   { name: 'Đá Scone', text: 'Công trình của bạn có thêm 1 độ bền khi dựng.' },
  compass: { name: 'La bàn', text: 'Đầu lượt, nếu tay còn 1 lá trở xuống thì rút thêm 1.' },
  seal:    { name: 'Ấn ngọc', text: 'Thuê lính rẻ hơn 1 vàng (tối thiểu 1). Bắt đầu với 1 vàng.' },
  jade:    { name: 'Ngọc tỷ', text: 'Máu tối đa +2.' },
  horn:    { name: 'Tù và chiến', text: 'Khi còn 4 máu trở xuống, mọi đòn của bạn gây thêm 1.' },
  banner:  { name: 'Cờ thánh', text: 'Lần đầu bị hạ về 0 máu, đứng dậy với 3 máu.' },
  shroud:  { name: 'Áo choàng thánh', text: 'Mỗi vòng, đòn đầu tiên nhắm vào bạn gây ít hơn 1.' },
  mint:    { name: 'Xưởng đúc tiền', text: 'Đầu mỗi lượt nhận 1 vàng.' },
};
const RELIC_IDS = Object.keys(RELICS);
