/* ── Content. Nothing here is a rule about regions: symbols go wherever history puts them. ── */
const START_HAND = 3;
/* each symbol resolves into steps; a card resolves its symbols left to right */
const SYM = {
  A: { name: 'Strike', desc: 'Deal 1 damage (walls take it first).', steps: [{ dmg: 1, basic: 1 }] },
  W: { name: 'Wall', desc: 'The card stays in play as a structure: 1 durability per wall icon.', steps: [] },
  H: { name: 'Heal', desc: 'Heal 1 HP.', steps: [{ heal: 1 }] },
  M: { name: 'Extra play', desc: 'Play another card.', steps: [{ plays: 1 }] },
  D: { name: 'Draw', desc: 'Draw 1 card.', steps: [{ draw: 1 }] },
  G: { name: 'Gold', desc: 'Gain 1 gold to hire mercenaries.', steps: [{ gold: 1 }] },
  R: { name: 'Raze', desc: "Destroy the opponent's biggest structure (a wonder loses 2 durability).", steps: [{ raze: 1 }] },
  S: { name: 'Steal', desc: "Steal 1 random card from an opponent's hand.", steps: [{ steal: 1 }] },
  C: { name: 'Convert', desc: "Convert the opponent's biggest structure to your side.", steps: [{ convert: 1 }] },
  K: { name: 'Cavalry', desc: 'Deal 2 damage. Camels block it.', steps: [{ dmg: 2, cav: 1 }] },
  E: { name: 'Elephant', desc: 'Destroy a structure, then deal 1 damage.', steps: [{ raze: 1 }, { dmg: 1 }] },
  L: { name: 'Camel', desc: 'Deal 1 damage and set up a camel guard: the next cavalry attack on you is cancelled (horses fear camels).', steps: [{ dmg: 1 }, { token: 'camel' }] },
  B: { name: 'Ranged', desc: 'Deal 1 damage over the walls, straight to HP.', steps: [{ dmg: 1, pierce: 1 }] },
  F: { name: 'Gunpowder', desc: 'Deal 1 damage to every opponent.', steps: [{ dmg: 1, all: 1 }] },
  Y: { name: 'Eagle', desc: 'Deal 1 damage, or 2 damage if the opponent has no walls.', steps: [{ dmg: 1, eagle: 1 }] },
  N: { name: 'Ship', desc: 'Raid: steal 1 card, then deal 1 damage.', steps: [{ steal: 1 }, { dmg: 1 }] },
};
const SYM_ORDER = 'AKEBLYFNRSCWHMDG';
const COMMON_NAMES = {
  A: 'Militia', AA: 'Swordsmen', AAA: 'Shock Troops', AM: 'Skirmish', AAM: 'Assault', AD: 'Outriders', AH: 'Spearmen',
  W: 'Palisade', WW: 'Stone Wall', WWW: 'Fortress', WH: 'Watch Tower',
  H: 'Provisions', HH: 'Healer', HD: 'Monastery', MD: 'Messenger', MM: 'Forced March', D: 'Scouting', DD: 'Scholars',
  G: 'Merchant', GG: 'Gold Mine', GD: 'Market Day', R: 'Battering Ram', S: 'Spy', C: 'Monk',
  K: 'Cavalry', KM: 'Light Cavalry', KK: 'Heavy Cavalry', E: 'War Elephant', EA: 'Elephant Charge', L: 'Camel Riders', LG: 'Caravan',
  B: 'Archers', BB: 'Arrow Volley', BM: 'Horse Archers', F: 'Fire Lances', FF: 'Bombards', Y: 'Eagle Warriors', YM: 'Eagle Scouts', N: 'Warship', NM: 'Landing Party',
};
/* signature cards: steps written by hand. wall kinds: regen (+1 per turn), sacred (heals owner each turn), thorns (hitting it hurts), fortress (raze removes only 1), wonder */
const UNIQUE = {
  greatwall: { name: "Great Wall", icons: 'WWWW', text: "A wall with 4 durability.", wall: 4 },
  exam: { name: "Imperial Exams", icons: 'DDG', text: "Draw 2 cards and gain 1 gold.", steps: [{ draw: 2 }, { gold: 1 }] },
  samurai: { name: "Samurai", icons: 'AA', text: "Deal 2 damage, or 3 damage if the opponent has no walls.", steps: [{ dmg: 2, samurai: 1 }] },
  kamikaze: { name: "Divine Wind", icons: 'D', text: "Until your next turn, every attack against you is cancelled. Draw 1 card.", steps: [{ token: 'immune' }, { draw: 1 }] },
  hwacha: { name: "Hwacha", icons: 'FF', text: "Deal 1 damage to every opponent, twice.", steps: [{ dmg: 1, all: 1 }, { dmg: 1, all: 1 }] },
  tripitaka: { name: "Tripitaka Koreana", icons: 'DDDM', text: "Draw 3 cards and play another card.", steps: [{ draw: 3 }, { plays: 1 }] },
  ironcav: { name: "Iron Pagoda", icons: 'KA', text: "Iron-clad cavalry: deal 3 damage. Camels block it.", steps: [{ dmg: 3, cav: 1 }] },
  thunder: { name: "Thunder Crash Bomb", icons: 'RF', text: "Destroy a structure, then deal 1 damage to every opponent.", steps: [{ raze: 1 }, { dmg: 1, all: 1 }] },
  stakes: { name: "Bạch Đằng Stakes", icons: 'W', text: "Until your next turn, the first opponent who damages you takes 2 damage.", steps: [{ token: 'trap' }] },
  proclaim: { name: "Call to Arms", icons: 'HHDD', text: "Heal 2 HP and draw 2 cards.", steps: [{ heal: 2 }, { draw: 2 }] },
  caravan: { name: "Desert Caravan", icons: 'LGD', text: "Deal 1 damage, set up a camel guard, gain 1 gold and draw 1 card.", steps: [{ dmg: 1 }, { token: 'camel' }, { gold: 1 }, { draw: 1 }] },
  baghdad: { name: "Baghdad Hospital", icons: 'HHH', text: "Heal 3 HP.", steps: [{ heal: 3 }] },
  immortals: { name: "Immortals", icons: 'WW', text: "A wall with 2 durability that regains 1 durability on each of your turns (max 3).", wall: 2, kind: 'regen' },
  sasanian: { name: "Sasanian Elephants", icons: 'EE', text: "Destroy two structures and deal 2 damage.", steps: [{ raze: 1 }, { dmg: 1 }, { raze: 1 }, { dmg: 1 }] },
  urban: { name: "Urban's Bombard", icons: 'RR', text: "Destroy every structure of one opponent, then deal 1 damage.", steps: [{ raze: 9 }, { dmg: 1 }] },
  janissary: { name: "Janissaries", icons: 'AAM', text: "Deal 2 damage and play another card.", steps: [{ dmg: 2 }, { plays: 1 }] },
  mansa: { name: "Mansa Musa's Pilgrimage", icons: 'GGG', text: "Gain 3 gold; your next hire this turn is free.", steps: [{ gold: 3 }, { buyFree: 1 }] },
  sankore: { name: "University of Sankore", icons: 'DDH', text: "Draw 2 cards and heal 1 HP.", steps: [{ draw: 2 }, { heal: 1 }] },
  lalibela: { name: "Churches of Lalibela", icons: 'WWW', text: "A wall with 3 durability; while it stands you heal 1 HP on each of your turns.", wall: 3, kind: 'sacred' },
  shotel: { name: "Shotel Warriors", icons: 'AAM', text: "Deal 2 damage and play another card.", steps: [{ dmg: 2 }, { plays: 1 }] },
  arrowrain: { name: "Arrow Storm", icons: 'BB', text: "Deal 1 damage over the walls to every opponent.", steps: [{ dmg: 1, pierce: 1, all: 1 }] },
  feint: { name: "Feigned Retreat", icons: 'RKA', text: "Lure them out: destroy a structure, then deal 2 damage.", steps: [{ raze: 1 }, { dmg: 2 }] },
  scourge: { name: "Scourge of God", icons: 'FS', text: "Every opponent discards a random card and takes 1 damage.", steps: [{ discard: 1, all: 1 }, { dmg: 1, all: 1 }] },
  aquileia: { name: "Sack of Aquileia", icons: 'SS', text: "Steal 2 cards from one opponent.", steps: [{ steal: 2 }] },
  twocourts: { name: "Dual Administration", icons: 'GGDM', text: "Gain 2 gold, draw 1 card and play another card.", steps: [{ gold: 2 }, { draw: 1 }, { plays: 1 }] },
  ordo: { name: "Ordo Camp", icons: 'WWH', text: "A wall with 2 durability; heal 1 HP.", wall: 2, steps: [{ heal: 1 }] },
  longbow: { name: "Longbow Volley", icons: 'BB', text: "Deal 2 damage over the walls.", steps: [{ dmg: 2, pierce: 1 }] },
  charter: { name: "Magna Carta", icons: 'GGH', text: "Gain 2 gold, heal 1 HP and draw 1 card.", steps: [{ gold: 2 }, { heal: 1 }, { draw: 1 }] },
  woad: { name: "Woad Raiders", icons: 'AAA', text: "Deal 3 damage; you lose 1 HP.", steps: [{ dmg: 3 }, { self: 1 }] },
  ambush: { name: "Highland Ambush", icons: 'FD', text: "Deal 1 damage to every opponent and draw 1 card.", steps: [{ dmg: 1, all: 1 }, { draw: 1 }] },
  paladin: { name: "Paladins", icons: 'KK', text: "Deal 4 damage. Camels block it.", steps: [{ dmg: 4, cav: 1 }] },
  charlemagne: { name: "Charlemagne", icons: 'HHW', text: "Heal 2 HP; all your structures gain 1 durability.", steps: [{ heal: 2 }, { fortify: 1 }] },
  berserk: { name: "Berserkers", icons: 'AAH', text: "Deal 2 damage and heal 1 HP.", steps: [{ dmg: 2 }, { heal: 1 }] },
  lindisfarne: { name: "Raid on Lindisfarne", icons: 'NS', text: "Steal 1 card from every opponent, then deal 1 damage.", steps: [{ steal: 1, all: 1 }, { dmg: 1 }] },
  teutonic: { name: "Teutonic Knights", icons: 'WWA', text: "A spiked wall with 2 durability: whoever hits it takes 1 damage.", wall: 2, kind: 'thorns' },
  marienburg: { name: "Marienburg Castle", icons: 'WWWW', text: "A wall with 4 durability.", wall: 4 },
  horde: { name: "Barbarian Horde", icons: 'MMD', text: "Play 2 more cards and draw 1 card.", steps: [{ plays: 2 }, { draw: 1 }] },
  sackrome: { name: "Sack of Rome", icons: 'RSA', text: "Destroy a structure, steal 1 card and deal 1 damage.", steps: [{ raze: 1 }, { steal: 1 }, { dmg: 1 }] },
  conquist: { name: "Conquistadors", icons: 'BB', text: "Guns and horses: deal 2 damage over the walls.", steps: [{ dmg: 2, pierce: 1 }] },
  reconq: { name: "Reconquista", icons: 'FH', text: "Deal 1 damage to every opponent and heal 1 HP.", steps: [{ dmg: 1, all: 1 }, { heal: 1 }] },
  caravel: { name: "Caravel", icons: 'NDM', text: "Steal 1 card, draw 1 card and play another card.", steps: [{ steal: 1 }, { draw: 1 }, { plays: 1 }] },
  indiaroute: { name: "Sea Route to India", icons: 'GGGM', text: "Gain 3 gold and play another card.", steps: [{ gold: 3 }, { plays: 1 }] },
  theodosius: { name: "Theodosian Walls", icons: 'WWW', text: "A wall with 3 durability that regains 1 durability on each of your turns (max 4).", wall: 3, kind: 'regen' },
  greekfire: { name: "Greek Fire", icons: 'RAA', text: "Destroy a structure, then deal 2 damage.", steps: [{ raze: 1 }, { dmg: 2 }] },
  sacrifice: { name: "Sacrifice", icons: 'DDM', text: "Lose 1 HP, draw 2 cards and play another card.", steps: [{ self: 1 }, { draw: 2 }, { plays: 1 }] },
  flowerwar: { name: "Flower War", icons: 'SY', text: "Take captives: steal 1 card, then deal 1 damage (2 damage if they have no walls).", steps: [{ steal: 1 }, { dmg: 1, eagle: 1 }] },
  chichen: { name: "Chichén Itzá", icons: 'WWW', text: "Wonder with 3 durability plus 1 per opponent; it takes hits before your walls. If it still stands at the start of your third turn after building it, you win. Raze, elephants and bombards remove 2 durability.", wonder: 1 },
  calendar: { name: "Maya Calendar", icons: 'DDH', text: "Draw 2 cards and heal 1 HP.", steps: [{ draw: 2 }, { heal: 1 }] },
  incaroad: { name: "Inca Road", icons: 'MDD', text: "Play another card and draw 2 cards.", steps: [{ plays: 1 }, { draw: 2 }] },
  sacsay: { name: "Sacsayhuamán", icons: 'WWW', text: "A wall with 3 durability made of giant stones: razing only removes 1 durability.", wall: 3, kind: 'fortress' },
  angkor: { name: "Angkor Wat", icons: 'WWW', text: "Wonder with 3 durability plus 1 per opponent; it takes hits before your walls. If it still stands at the start of your third turn after building it, you win. Raze, elephants and bombards remove 2 durability.", wonder: 1 },
  baray: { name: "Baray Reservoir", icons: 'HHG', text: "Heal 2 HP and gain 1 gold.", steps: [{ heal: 2 }, { gold: 1 }] },
  armoredel: { name: "Armored Elephants", icons: 'EE', text: "Destroy two structures and deal 2 damage.", steps: [{ raze: 1 }, { dmg: 1 }, { raze: 1 }, { dmg: 1 }] },
  cholafleet: { name: "Chola Fleet", icons: 'NF', text: "Deal 1 damage to every opponent, then steal 1 card.", steps: [{ dmg: 1, all: 1 }, { steal: 1 }] },
};
/* civs: hp2 (duel) and hp4 (3–4 players) come from tune.js (AI vs AI); deck = 24 cards; group only helps browsing */
const CIVS = {
  chinese: { name: "Chinese", group: "East Asia", color: '#b3261e', charge: 'sun', hp2: 14, hp4: 12, style: "Gunpowder, great walls, imperial exams", deck: 'A3 AA1 AM2 F3 FF1 W2 WW1 WH1 H2 HD1 DD1 G1 R1 AA1 C1 +greatwall +exam' },
  japanese: { name: "Japanese", group: "East Asia", color: '#c0392b', charge: 'disc', hp2: 12, hp4: 14, style: "Samurai strikes, the Divine Wind shields", deck: 'A5 AA2 AM2 AAM1 K1 B2 W2 WH1 H2 HH1 D1 MD1 G1 +samurai +kamikaze' },
  koreans: { name: "Koreans", group: "East Asia", color: '#2b6cb0', charge: 'knot', hp2: 15, hp4: 13, style: "Rocket carts, sturdy walls, card draw", deck: 'A3 AA3 AM2 F3 B2 W1 WW1 WH1 H2 HH1 D1 G1 R1 +hwacha +tripitaka' },
  jurchens: { name: "Jurchens", group: "East Asia", color: '#3d4f5c', charge: 'axe', hp2: 9, hp4: 13, style: "Iron cavalry and thunder bombs", deck: 'A5 AA2 AM1 AAM1 K2 KM1 KK1 F1 W2 WH1 H2 D1 G1 R1 +ironcav +thunder' },
  daiviet: { name: "Đại Việt", group: "Southeast Asia", color: '#b8860b', charge: 'star', hp2: 15, hp4: 14, style: "Crossbows, elephants, the Bạch Đằng stakes", deck: 'A4 AA2 AM1 AD1 B3 BB1 E2 W2 WW1 WH1 H2 HH1 D1 +stakes +proclaim' },
  khmer: { name: "Khmer", group: "Southeast Asia", color: '#8a5a2b', charge: 'temple', hp2: 9, hp4: 12, style: "War elephants and Angkor Wat", deck: 'A4 AA1 AM1 E2 EA1 B1 W2 WW1 WH1 H2 HH1 D1 G2 C1 R1 +angkor +baray' },
  indians: { name: "Indians", group: "South Asia", color: '#d97706', charge: 'wheel', hp2: 12, hp4: 12, style: "Armored elephants and the Chola fleet", deck: 'A4 AA2 AM1 E2 EA2 N1 L1 W2 WH1 H2 HH1 D1 C1 R1 +armoredel +cholafleet' },
  arabs: { name: "Arabs", group: "Middle East & Africa", color: '#1f7a4d', charge: 'crescent', hp2: 10, hp4: 11, style: "Camels, caravans, medicine", deck: 'A4 AM1 L3 LG1 K1 W2 WH1 H2 HH2 HD1 C1 G1 GD1 S1 +caravan +baghdad' },
  persians: { name: "Persians", group: "Middle East & Africa", color: '#6b2d8f', charge: 'sun', hp2: 13, hp4: 12, style: "Elephants, camels and the Immortals", deck: 'A4 AA1 AM1 E2 EA1 L2 K1 W2 WH1 H2 HH1 D1 G1 R1 C1 +immortals +sasanian' },
  turks: { name: "Turks", group: "Middle East & Africa", color: '#a51c30', charge: 'crescent', hp2: 14, hp4: 12, style: "Great bombards, Janissaries, gunpowder", deck: 'A4 AA1 AM2 F2 FF1 L1 K1 W2 WH1 H2 D1 G2 R2 +urban +janissary' },
  malians: { name: "Malians", group: "Middle East & Africa", color: '#c08a1e', charge: 'disc', hp2: 10, hp4: 11, style: "Gold, mercenaries, camels", deck: 'A4 AM2 L2 LG1 G2 GG1 W2 WH1 H2 HH1 D1 S1 K1 AA1 +mansa +sankore' },
  ethiopians: { name: "Ethiopians", group: "Middle East & Africa", color: '#2f7d32', charge: 'cross', hp2: 14, hp4: 11, style: "Healing rock churches, Shotel warriors", deck: 'A5 AA1 AM1 E1 L1 B1 W2 WW1 WH1 H2 HH2 HD1 C1 D1 G1 +lalibela +shotel' },
  mongols: { name: "Mongols", group: "Steppe", color: '#1f6f8b', charge: 'horse', hp2: 14, hp4: 14, style: "Relentless horse archers, feigned retreats", deck: 'A3 AM2 B3 BM3 K1 KM1 MD1 W1 WH1 H2 D1 S1 G1 R1 +arrowrain +feint' },
  huns: { name: "Huns", group: "Steppe", color: '#7a3b12', charge: 'bow', hp2: 13, hp4: 14, style: "Ravage, plunder, horse archers", deck: 'A4 AA1 AM2 AAM1 B2 BM2 K1 KM1 S2 W1 WH1 H2 D1 R1 +scourge +aquileia' },
  khitans: { name: "Khitans", group: "Steppe", color: '#4a6b3a', charge: 'bow', hp2: 11, hp4: 12, style: "Rich dual courts, nomad camps", deck: 'A4 AM1 B2 BM2 K2 KM1 W2 WH1 H2 HH1 D1 G2 R1 +twocourts +ordo' },
  britons: { name: "Britons", group: "Europe", color: '#9b1c1c', charge: 'tower', hp2: 14, hp4: 14, style: "Longbows that shoot over walls", deck: 'A3 AM1 B4 BB2 AD1 K1 W2 WW1 WH1 H2 HH1 D1 G1 R1 +longbow +charter' },
  celts: { name: "Celts", group: "Europe", color: '#1d6b45', charge: 'knot', hp2: 11, hp4: 15, style: "Frenzied infantry, ambushes", deck: 'A5 AA3 AM2 AAM1 AD1 AH1 W2 WH1 H2 HH1 D1 S1 R1 +woad +ambush' },
  franks: { name: "Franks", group: "Europe", color: '#1f4e9c', charge: 'fleur', hp2: 9, hp4: 13, style: "Knights and castles", deck: 'A4 AA1 AM1 K3 KK1 KM1 W2 WW1 WH1 H2 HH1 C1 D1 G1 R1 +paladin +charlemagne' },
  vikings: { name: "Vikings", group: "Europe", color: '#33506b', charge: 'ship', hp2: 11, hp4: 14, style: "Longship raids, berserkers", deck: 'A4 AA2 AM2 AAM1 N3 NM1 S1 W2 WH1 H2 HH1 D1 G1 +berserk +lindisfarne' },
  teutons: { name: "Teutons", group: "Europe", color: '#2d2d2d', charge: 'cross', hp2: 14, hp4: 12, style: "Spiked walls, heavy knights", deck: 'A3 AA2 K2 KK1 W3 WW2 WWW1 WH1 H2 HH1 C1 D1 R1 G1 +teutonic +marienburg' },
  goths: { name: "Goths", group: "Europe", color: '#5b4636', charge: 'axe', hp2: 11, hp4: 14, style: "Human waves, the Sack of Rome", deck: 'A5 AA2 AM3 AAM1 MM1 AD1 W2 WH1 H3 D1 S1 R1 +horde +sackrome' },
  spanish: { name: "Spanish", group: "Europe", color: '#b45309', charge: 'tower', hp2: 13, hp4: 13, style: "Conquistadors, gold, Reconquista", deck: 'A3 AA1 AM1 AH1 K2 KM1 B1 W2 WW1 WH1 H2 C1 D1 G2 GD1 R1 +conquist +reconq' },
  portuguese: { name: "Portuguese", group: "Europe", color: '#0e5e6f', charge: 'quinas', hp2: 10, hp4: 12, style: "Caravels and sea trade", deck: 'A3 AA1 AM2 N2 NM1 B1 W2 WH1 H2 HH1 D1 MD1 G2 BB1 FF1 +caravel +indiaroute' },
  byzantines: { name: "Byzantines", group: "Europe", color: '#5b2a86', charge: 'cross', hp2: 15, hp4: 13, style: "Theodosian Walls, Greek fire, cataphracts", deck: 'A3 AA1 AM1 K2 W3 WW2 WH1 H2 HH2 HD1 C1 D1 G1 R1 +theodosius +greekfire' },
  aztecs: { name: "Aztecs", group: "Americas", color: '#0f766e', charge: 'eagle', hp2: 10, hp4: 14, style: "Sacrifice and Eagle warriors", deck: 'A4 AA2 AM1 AAM1 Y3 YM1 B1 S1 W1 WH1 H2 HH1 D1 G1 C1 +sacrifice +flowerwar' },
  mayans: { name: "Mayans", group: "Americas", color: '#2e7d5b', charge: 'pyramid', hp2: 9, hp4: 13, style: "Chichén Itzá and archers", deck: 'A4 AM1 Y2 B2 BB1 W2 WW1 WH1 H2 HH1 D1 DD1 G1 R1 C1 +chichen +calendar' },
  incas: { name: "Incas", group: "Americas", color: '#c2410c', charge: 'sun', hp2: 15, hp4: 14, style: "Swift Inca roads, stone fortresses", deck: 'A3 AA2 AM2 MD1 B2 BB1 Y1 W2 WW1 WH1 H2 HH1 D1 S1 R1 +incaroad +sacsay' },
};
const CIV_ORDER = Object.keys(CIVS);
const GROUPS = ['East Asia', 'Southeast Asia', 'South Asia', 'Middle East & Africa', 'Steppe', 'Europe', 'Americas'];
/* the mercenary market: neutral cards anyone can hire with gold */
const MERCS = [
  { id: 'genoa', name: "Genoese Crossbowmen", icons: 'BBM', cost: 2, n: 2 },
  { id: 'crusader', name: "Crusaders", icons: 'KAM', cost: 2, n: 2 },
  { id: 'engineer', name: "Siege Engineers", icons: 'RWWM', cost: 2, n: 2 },
  { id: 'trebuchet', name: "Trebuchet", icons: 'RR', cost: 3, n: 1, steps: [{ raze: 1 }, { raze: 1 }] },
  { id: 'physician', name: "Physician", icons: 'HHHD', cost: 2, n: 2 },
  { id: 'venetian', name: "Venetian Merchants", icons: 'GGDM', cost: 1, n: 2 },
  { id: 'varangian', name: "Varangian Guard", icons: 'KKWW', cost: 3, n: 1 },
  { id: 'cuman', name: "Cuman Horse Archers", icons: 'BBM', cost: 2, n: 2 },
  { id: 'assassin', name: "Hashashin", icons: 'BBB', cost: 3, n: 1, text: 'Deal 3 damage over the walls.', steps: [{ dmg: 3, pierce: 1 }] },
  { id: 'envoy', name: "Envoy", icons: 'SSM', cost: 2, n: 1 },
  { id: 'templar', name: "Knights Templar", icons: 'CKH', cost: 3, n: 1 },
  { id: 'gunners', name: "Hungarian Gunners", icons: 'FFF', cost: 3, n: 1 },
  { id: 'warel', name: "Hired Elephants", icons: 'EA', cost: 2, n: 1 },
  { id: 'bedouin', name: "Bedouin Camels", icons: 'LLM', cost: 2, n: 1 },
];
/* events: one per round, the next one is always visible */
const EVENTS = [
  { id: 'plague', name: 'Plague', text: 'Everyone loses 1 HP.' },
  { id: 'harvest', name: 'Harvest', text: 'Everyone heals 1 HP.' },
  { id: 'silkroad', name: 'Silk Road Open', text: 'Everyone gains 1 gold.' },
  { id: 'winter', name: 'Harsh Winter', text: 'Every structure loses 1 durability.' },
  { id: 'fair', name: 'Great Fair', text: 'The market restocks 3 new cards; hiring costs 1 less gold this round.' },
  { id: 'feast', name: 'Spring Festival', text: 'Everyone draws 1 card.' },
  { id: 'revolt', name: 'Peasant Revolt', text: 'Whoever has the most HP loses 1 HP.' },
  { id: 'crusade', name: 'Crusade', text: 'This round every Strike icon deals 1 extra damage.' },
  { id: 'monsoon', name: 'Monsoon', text: 'No one can build structures this round.' },
  { id: 'flood', name: 'Flood', text: 'Everyone discards 1 random card.' },
  { id: 'eclipse', name: 'Eclipse', text: 'Everyone passes 1 random card to the next player.' },
  { id: 'bells', name: 'Church Bells', text: 'Whoever has the least HP heals 2 HP.' },
];
/* relics: pick 1 of 3 at the start */
const RELICS = {
  joyeuse: { name: 'Joyeuse', text: 'Your first damaging card each turn deals 1 extra damage.' },
  grail:   { name: 'Holy Grail', text: 'Your first healing card each turn heals 1 extra HP.' },
  scone:   { name: 'Stone of Scone', text: 'Your structures get 1 extra durability when built.' },
  compass: { name: 'Compass', text: 'At the start of your turn, if you hold 1 card or fewer, draw 1 extra card.' },
  seal:    { name: "Merchant's Seal", text: 'Hiring costs 1 less gold (minimum 1). Start with 1 gold.' },
  jade:    { name: 'Imperial Jade', text: 'Your max HP is 2 higher.' },
  horn:    { name: 'War Horn', text: 'While you have 4 HP or less, your attacks deal 1 extra damage.' },
  banner:  { name: 'Holy Banner', text: 'The first time you drop to 0 HP, rise again with 3 HP.' },
  shroud:  { name: 'Holy Mantle', text: 'Each round, the first attack against you deals 1 less damage.' },
  mint:    { name: 'Royal Mint', text: 'Gain 1 gold at the start of each of your turns.' },
};
const RELIC_IDS = Object.keys(RELICS);
